export { default as HeroSection } from './HeroSection'
export { default as TaglineSection } from './TaglineSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as FeatureCardsSection } from './FeatureCardsSection'
export { default as StudentFeaturesSection } from './StudentFeaturesSection'
export { default as LiveTuitionSection } from './LiveTuitionSection'
export { default as DownloadSection } from './DownloadSection'
